Repository BlazingDB/blazingsql, pull requests merged in 2020-04, with the labels that each got.

#542 [REVIEW] update dependency version in readme
  README.md
Labels: ! - Hotfix

#569 Update README.md
  README.md
Labels: code quality, feature request

#571 Update README.md
  README.md
Labels: code quality
